CREATE TABLE school_score_line (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  year INT NOT NULL,
  category_code VARCHAR(20) NOT NULL,
  category_name VARCHAR(100) NOT NULL,
  degree_type VARCHAR(20) NOT NULL,
  total_score INT,
  politics_score INT,
  foreign_language_score INT,
  subject_one_score INT,
  subject_two_score INT,
  score_100 INT,
  score_over_100 INT,
  availability_status VARCHAR(30) NOT NULL,
  source_id BIGINT,
  source_title VARCHAR(255) NOT NULL,
  article_url VARCHAR(500) NOT NULL,
  article_sha256 VARCHAR(64) NOT NULL,
  image_url VARCHAR(500),
  image_sha256 VARCHAR(64),
  published_date DATE,
  scope_note VARCHAR(500) NOT NULL,
  remark VARCHAR(1000),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_school_score_line (school_id, year, category_code, degree_type),
  KEY idx_school_score_line_school_year (school_id, year),
  KEY idx_school_score_line_status (availability_status),
  CONSTRAINT fk_school_score_line_school FOREIGN KEY (school_id) REFERENCES school(id),
  CONSTRAINT fk_school_score_line_source FOREIGN KEY (source_id) REFERENCES document_source(id)
);
