CREATE TABLE web_capture_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  target_id BIGINT NOT NULL,
  requested_url VARCHAR(500) NOT NULL,
  final_url VARCHAR(500),
  content_sha256 VARCHAR(64),
  http_status INT,
  content_type VARCHAR(100),
  response_size BIGINT NOT NULL DEFAULT 0,
  extractor_version VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  title VARCHAR(255),
  raw_text LONGTEXT,
  extracted_length INT NOT NULL DEFAULT 0,
  reuse_count INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000),
  operator VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completed_at DATETIME,
  UNIQUE KEY uk_web_capture_target_hash (target_id, content_sha256),
  KEY idx_web_capture_status_time (status, updated_at),
  KEY idx_web_capture_target_time (target_id, updated_at)
);
