CREATE TABLE IF NOT EXISTS school (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  province VARCHAR(50),
  city VARCHAR(50),
  region VARCHAR(50),
  school_level VARCHAR(50),
  is_985 TINYINT DEFAULT 0,
  is_211 TINYINT DEFAULT 0,
  is_double_first_class TINYINT DEFAULT 0,
  is_self_determined_score TINYINT DEFAULT 0,
  official_site VARCHAR(255),
  graduate_site VARCHAR(255),
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name)
);

ALTER TABLE school ADD COLUMN IF NOT EXISTS is_self_determined_score TINYINT DEFAULT 0;

CREATE TABLE IF NOT EXISTS college (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  official_site VARCHAR(255),
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS major (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  major_code VARCHAR(50),
  degree_type VARCHAR(20),
  research_direction TEXT,
  study_mode VARCHAR(20),
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE major ALTER COLUMN research_direction TEXT;

CREATE TABLE IF NOT EXISTS document_source (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  source_type VARCHAR(50),
  source_url VARCHAR(500),
  publish_date DATE,
  school_id BIGINT,
  college_id BIGINT,
  year INT,
  is_official TINYINT DEFAULT 1,
  audit_status VARCHAR(20) DEFAULT 'PUBLISHED',
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS source_document (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  document_type VARCHAR(50),
  source_url VARCHAR(500),
  school_id BIGINT,
  college_id BIGINT,
  major_id BIGINT,
  year INT,
  audit_status VARCHAR(20) DEFAULT 'DRAFT',
  source_reliability VARCHAR(20) DEFAULT 'UNKNOWN',
  raw_text CLOB,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS document_chunk (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  document_id BIGINT NOT NULL,
  school_id BIGINT,
  college_id BIGINT,
  major_id BIGINT,
  year INT,
  document_type VARCHAR(50),
  chunk_index INT NOT NULL,
  content CLOB NOT NULL,
  page_number INT,
  audit_status VARCHAR(20) DEFAULT 'DRAFT',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS source_document_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  document_type VARCHAR(50),
  source_url VARCHAR(500),
  school_id BIGINT,
  college_id BIGINT,
  major_id BIGINT,
  year INT,
  audit_status VARCHAR(20),
  source_reliability VARCHAR(20),
  raw_text CLOB,
  remark VARCHAR(500),
  operation VARCHAR(20) NOT NULL,
  operator VARCHAR(100) NOT NULL,
  source_updated_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (document_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_source_document_version_document
  ON source_document_version(document_id, version_no);

CREATE TABLE IF NOT EXISTS document_publication_batch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(20) NOT NULL,
  document_count INT NOT NULL,
  chunk_count INT NOT NULL DEFAULT 0,
  rollback_chunk_count INT,
  reason VARCHAR(500),
  operator VARCHAR(100) NOT NULL,
  rollback_reason VARCHAR(500),
  rollback_operator VARCHAR(100),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP,
  rolled_back_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_document_publication_batch_status_time
  ON document_publication_batch(status, created_at);

CREATE TABLE IF NOT EXISTS document_publication_batch_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  document_id BIGINT NOT NULL,
  previous_version_no INT NOT NULL,
  published_version_no INT NOT NULL,
  rollback_version_no INT,
  previous_audit_status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (batch_id, document_id),
  FOREIGN KEY (batch_id) REFERENCES document_publication_batch(id)
);

CREATE INDEX IF NOT EXISTS idx_document_publication_item_document
  ON document_publication_batch_item(document_id, batch_id);

CREATE TABLE IF NOT EXISTS admission_plan (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  year INT NOT NULL,
  total_quota INT,
  recommended_quota INT,
  unified_quota INT,
  has_adjustment TINYINT DEFAULT 0,
  source_id BIGINT,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exam_subject (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  year INT NOT NULL,
  politics VARCHAR(100),
  foreign_language VARCHAR(100),
  math_subject VARCHAR(100),
  professional_subject VARCHAR(100),
  is_408 TINYINT DEFAULT 0,
  reference_books CLOB,
  source_id BIGINT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS score_line (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  year INT NOT NULL,
  total_score INT,
  politics_score INT,
  foreign_language_score INT,
  math_score INT,
  professional_score INT,
  source_id BIGINT,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS national_score_line (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  year INT NOT NULL,
  category_code VARCHAR(20) NOT NULL,
  category_name VARCHAR(100) NOT NULL,
  candidate_type VARCHAR(10) NOT NULL,
  total_score INT NOT NULL,
  score_100 INT NOT NULL,
  score_over_100 INT NOT NULL,
  source_title VARCHAR(255) NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  published_date VARCHAR(20),
  source_hash VARCHAR(64),
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (year, category_code, candidate_type)
);

CREATE TABLE IF NOT EXISTS school_score_line (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  year INT NOT NULL,
  category_code VARCHAR(20) NOT NULL,
  category_name VARCHAR(100) NOT NULL,
  degree_type VARCHAR(20) NOT NULL,
  total_score INT,
  politics_score INT,
  foreign_language_score INT,
  subject_one_score INT,
  subject_two_score INT,
  score_100 INT,
  score_over_100 INT,
  availability_status VARCHAR(30) NOT NULL,
  source_id BIGINT,
  source_title VARCHAR(255) NOT NULL,
  article_url VARCHAR(500) NOT NULL,
  article_sha256 VARCHAR(64) NOT NULL,
  image_url VARCHAR(500),
  image_sha256 VARCHAR(64),
  published_date DATE,
  scope_note VARCHAR(500) NOT NULL,
  remark VARCHAR(1000),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (school_id, year, category_code, degree_type)
);

CREATE TABLE IF NOT EXISTS admission_result (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  year INT NOT NULL,
  admitted_count INT,
  lowest_score INT,
  average_score DOUBLE,
  highest_score INT,
  retest_ratio DOUBLE,
  source_id BIGINT,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admission_result_import_batch (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  year INT NOT NULL,
  source_id BIGINT NOT NULL,
  source_sha256 VARCHAR(64) NOT NULL,
  batch_sha256 VARCHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  input_records INT NOT NULL,
  group_count INT NOT NULL,
  mapped_group_count INT NOT NULL,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at DATETIME,
  UNIQUE (batch_sha256)
);

CREATE TABLE IF NOT EXISTS admission_result_candidate (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  candidate_key VARCHAR(64) NOT NULL,
  college_name VARCHAR(100) NOT NULL,
  major_code VARCHAR(50) NOT NULL,
  major_name VARCHAR(100),
  degree_type VARCHAR(20) NOT NULL,
  study_mode VARCHAR(20) NOT NULL,
  candidate_type VARCHAR(50) NOT NULL,
  initial_score INT,
  retest_score DOUBLE,
  final_score DOUBLE,
  special_program VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (batch_id, candidate_key)
);

CREATE TABLE IF NOT EXISTS retest_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT,
  major_id BIGINT,
  year INT NOT NULL,
  retest_time VARCHAR(255),
  retest_method VARCHAR(255),
  retest_ratio DOUBLE,
  initial_score_weight INT,
  retest_score_weight INT,
  qualification_line CLOB,
  materials CLOB,
  source_id BIGINT,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE retest_rule ALTER COLUMN college_id DROP NOT NULL;
ALTER TABLE retest_rule ALTER COLUMN major_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS reference_book (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  year INT NOT NULL,
  subject_name VARCHAR(255),
  book_title VARCHAR(255),
  author VARCHAR(255),
  edition VARCHAR(100),
  publisher VARCHAR(255),
  source_id BIGINT,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS adjustment_info (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  major_id BIGINT NOT NULL,
  year INT NOT NULL,
  title VARCHAR(255),
  is_open TINYINT DEFAULT 0,
  vacancy_count INT,
  application_window VARCHAR(255),
  requirements CLOB,
  notice_url VARCHAR(500),
  source_id BIGINT,
  remark VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_conversation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  question CLOB NOT NULL,
  answer CLOB,
  related_school_id BIGINT,
  related_major_id BIGINT,
  source_summary CLOB,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalog_import_batch (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  catalog_type VARCHAR(50) NOT NULL,
  year INT NOT NULL,
  retrieved_at VARCHAR(50),
  is_complete TINYINT DEFAULT 0,
  input_records INT NOT NULL,
  school_count INT NOT NULL,
  batch_sha256 VARCHAR(64) NOT NULL,
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (catalog_type, year, batch_sha256)
);

CREATE TABLE IF NOT EXISTS admin_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(50),
  role VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
  status TINYINT NOT NULL DEFAULT 1,
  last_login_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS admin_session (
  token_hash VARCHAR(64) PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  role VARCHAR(30) NOT NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES admin_user(username)
);

CREATE INDEX IF NOT EXISTS idx_admin_session_expiry ON admin_session(expires_at);
CREATE INDEX IF NOT EXISTS idx_admin_session_username ON admin_session(username);

CREATE TABLE IF NOT EXISTS document_parse_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  file_sha256 VARCHAR(64) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  content_type VARCHAR(100),
  file_size BIGINT NOT NULL,
  parser_type VARCHAR(30) NOT NULL,
  parser_version VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  document_type VARCHAR(50),
  title VARCHAR(255),
  raw_text CLOB,
  remark VARCHAR(500),
  extracted_length INT NOT NULL DEFAULT 0,
  reuse_count INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000),
  operator VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  UNIQUE (file_sha256)
);

CREATE INDEX IF NOT EXISTS idx_document_parse_task_status_time
  ON document_parse_task(status, updated_at);

CREATE TABLE IF NOT EXISTS web_capture_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  target_id BIGINT NOT NULL,
  requested_url VARCHAR(500) NOT NULL,
  final_url VARCHAR(500),
  content_sha256 VARCHAR(64),
  http_status INT,
  content_type VARCHAR(100),
  response_size BIGINT NOT NULL DEFAULT 0,
  extractor_version VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  title VARCHAR(255),
  raw_text CLOB,
  extracted_length INT NOT NULL DEFAULT 0,
  reuse_count INT NOT NULL DEFAULT 0,
  error_message VARCHAR(1000),
  operator VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  UNIQUE (target_id, content_sha256)
);

CREATE INDEX IF NOT EXISTS idx_web_capture_status_time
  ON web_capture_task(status, updated_at);
CREATE INDEX IF NOT EXISTS idx_web_capture_target_time
  ON web_capture_task(target_id, updated_at);

CREATE TABLE IF NOT EXISTS web_capture_change (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_id BIGINT NOT NULL,
  previous_task_id BIGINT NOT NULL,
  current_task_id BIGINT NOT NULL,
  previous_sha256 VARCHAR(64) NOT NULL,
  current_sha256 VARCHAR(64) NOT NULL,
  previous_length INT NOT NULL,
  current_length INT NOT NULL,
  added_line_count INT NOT NULL,
  removed_line_count INT NOT NULL,
  change_ratio DECIMAL(6,4) NOT NULL,
  previous_excerpt VARCHAR(2000),
  current_excerpt VARCHAR(2000),
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING_REVIEW',
  review_note VARCHAR(500),
  reviewer VARCHAR(100),
  detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_web_capture_change_status_time
  ON web_capture_change(status, detected_at);
CREATE INDEX IF NOT EXISTS idx_web_capture_change_target_time
  ON web_capture_change(target_id, detected_at);

CREATE TABLE IF NOT EXISTS data_change_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  operator VARCHAR(50),
  action VARCHAR(20) NOT NULL,
  resource_path VARCHAR(255) NOT NULL,
  status_code INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS data_collection_task (
  school_id BIGINT PRIMARY KEY,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  assignee VARCHAR(100),
  due_date DATE,
  completion_criteria VARCHAR(1000) NOT NULL,
  criteria_custom TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME
);

CREATE TABLE IF NOT EXISTS data_collection_target (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  title VARCHAR(200) NOT NULL,
  document_type VARCHAR(50) NOT NULL,
  target_year INT NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  note VARCHAR(500),
  system_generated TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (school_id, document_type, target_year, source_url)
);

CREATE TABLE IF NOT EXISTS web_capture_schedule (
  target_id BIGINT PRIMARY KEY,
  enabled TINYINT NOT NULL DEFAULT 0,
  interval_hours INT NOT NULL DEFAULT 24,
  next_run_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lease_owner VARCHAR(100),
  lease_until DATETIME,
  last_started_at DATETIME,
  last_finished_at DATETIME,
  last_status VARCHAR(20),
  last_error VARCHAR(500),
  consecutive_failures INT NOT NULL DEFAULT 0,
  updated_by VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_web_capture_schedule_target FOREIGN KEY (target_id)
    REFERENCES data_collection_target(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_web_capture_schedule_due
  ON web_capture_schedule(enabled, next_run_at, lease_until);

CREATE TABLE IF NOT EXISTS data_collection_task_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  school_id BIGINT NOT NULL,
  action VARCHAR(30) NOT NULL,
  from_status VARCHAR(20),
  to_status VARCHAR(20),
  operator VARCHAR(100),
  detail VARCHAR(1000),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
